### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by ArefMozafari** [MarkSnaile/telegram-channel-views-boost#13]
this is what i get when i try to use the program:
![Screen Shot 1398-01-28 at 21 08 31](https://user-images.githubusercontent.com/29792606/56305540-cd8a0600-6155-11e9-9a9f-6a0faa0fafcd.png)

what is this for?

**Comment by partizanfm88** [comment]
You have to download requests module for you python 3 using pip install. But this is not a problem. The problem is that this whole script stopped work 2 weeks ago after telegram update.

**Comment by ArefMozafari** [comment]
thank you by the way.

**Comment by fredericofeliz** [comment]
@partizanfm88 did you found a way to fix this problem? 
Traceback (most recent call last):
  File "C:\Users\Felizzz\Desktop\tg_boost.py", line 50, in <module>
    thread = threading.Thread(target=run,args=(sys.argv[1],sys.argv[2],p))
IndexError: list index out of range
