### ISSUE TITLE
DOESN'T WORK

### ISSUE THREAD

**Issue by aleff-github** [MarkSnaile/telegram-channel-views-boost#20]
It doesn't work

**Comment by vijaykrishna0** [comment]
> It doesn't work

Did you find any solution or alternative?

**Comment by NoNameoN-A** [comment]
I didn’t found a solution because if you use a proxy it doesn’t work...
It doesn’t count the view, I don’t know why...
I think that we must use a private proxy, good non-free vpn and a tor connection but they can understand if you use a tor connection so I don’t want to risk :-/

> Alessandro Greco
> Sito Web:[www.nonameon.altervista.org/](http://nonameon.altervista.org/)
> Interessati:www.interessati.com
> Telefono: +39 327 83 21 517
> Whatsapp: NO | Signal: SI
